tasks:
    - concorsi:
        - host:
            url: http://concorsi.it
            login:
                user: enrico
                password: pipppo
            tables:
               - concorsi:
                   table_url: "/concorsi"
                   selector: "myselector"
                   htmlentryincl: ["",""]
                   htmlentryexcl: ["",""]
        - host:
            url: http://concorsi.it
            login:
                user: enrico
                password: pipppo
            tables:
               - concorsi:
                   table_url: "/concorsi"
                   selector: "myselector"
                   htmlentryincl: ["",""]
                   htmlentryexcl: ["",""]



    - italianpenpals:
        - host:
            url: http://concorsi.it
            login:
                user: enrico
                password: pipppo
            tables:
               concorsi:
                   url: "/concorsi"
                   selector: "myselector"




l1entry2: ciao

l1entry3:
    - l2entry: saluti